In [2]:
import numpy as np

In [3]:
list1=[5,3,4,2]
arr=np.array(list1)
arr

array([5, 3, 4, 2])

In [4]:
arr.data

In [8]:
#datatype of arr
arr.dtype

dtype('int32')

In [9]:
#conversion of datatype
arr.astype('float32')

array([5., 3., 4., 2.], dtype=float32)

In [15]:
#numbers between 0 to 10
arr=np.arange(0,9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
#shape of arr is 1d 9 elements
arr.shape

(9,)

In [21]:
arr.size

9

In [22]:
#dimension of arr is 1--1d array
arr.ndim

1

In [26]:
#size occupied by elements
arr.itemsize

4

In [27]:
#size occupied by arr
arr.nbytes

36

In [13]:
#numbers from 0 to 21 with 5 steps
np.arange(0,21,5)

array([ 0,  5, 10, 15, 20])

In [17]:
#numbers from 20 to -5 with -5 steps descending
np.arange(20,-5,-5)

array([20, 15, 10,  5,  0])

In [29]:
#array of 5 zeros with data type of int
np.zeros(5).astype('int32')

array([0, 0, 0, 0, 0])

In [30]:
#array of 7 ones
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [31]:
#array of 2s 6 times
np.full(6,2)

array([2, 2, 2, 2, 2, 2])

In [32]:
#repeat each element 2 times
np.repeat([10,12,13],2)

array([10, 10, 12, 12, 13, 13])

In [33]:
#array a with odd numbers between 0 and 10
a=np.arange(0,10)
a[a%2!=0]

array([1, 3, 5, 7, 9])

In [34]:
#array a with even numbers
a[a%2==0]

array([0, 2, 4, 6, 8])

In [42]:
#linearly spaced elements
linspace= (stop-start)/(num of elements-1)
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [71]:
#uniform distribution --probablity  between 0 and 1
np.random.rand(1)

array([0.92958908])

In [94]:
#1 row 2 columns
np.random.rand(1,2)

array([[0.26341111, 0.01634387]])

In [92]:
#1 block 2 rows 3 columns
np.random.rand(1,2,3)

array([[[0.49914474, 0.6264674 , 0.09212936],
        [0.0111381 , 0.92008543, 0.26834923]]])

In [17]:
#generate numbers between two values along with size specified--3 blocks 2 rows each 5 columns each
np.random.uniform(10,20,size=(3,2,5))

array([[[18.6250187 , 18.57694774, 15.8536602 , 15.3853281 ,
         10.97300925],
        [16.62404808, 15.2782354 , 12.22468631, 17.25441719,
         19.79323302]],

       [[16.53080591, 14.650267  , 14.42745591, 11.04298982,
         11.14899701],
        [14.89534397, 17.42938058, 17.20621084, 16.32270052,
         17.72908496]],

       [[14.12640967, 14.7088265 , 11.99263485, 16.97696751,
         18.63003888],
        [11.43671746, 18.65608596, 15.57350026, 11.95712753,
         19.52487301]]])

In [88]:
#generating random integers
np.random.randint(10,20,5)

array([19, 17, 13, 10, 19])

In [98]:
#traversal
a=[3,7,5,8,10]
for i,j in np.ndenumerate(a):
    print(i,j)


(0,) 3
(1,) 7
(2,) 5
(3,) 8
(4,) 10


In [100]:
np.mean(a)

6.6

In [101]:
np.sum(a)

33

In [102]:
#cumulative sum of elements
np.cumsum(a)

array([ 3, 10, 15, 23, 33], dtype=int32)

In [105]:
np.median(a)

7.0

In [107]:
#variance
np.var(a)

5.84

In [109]:
np.min(a)

3

In [110]:
np.max(a)

10

In [111]:
#index of min element
np.argmin(a)

0

In [112]:
#index of max element
np.argmax(a)

4

In [3]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.max(a)

9

In [9]:
np.max([a[0]])

3

In [10]:
np.max([a[2]])

9

In [19]:
np.transpose(a)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [13]:
for i,j,value in a:
    np.ndenumerate(a)
    print(i,j,value)

1 2 3
4 5 6
7 8 9


In [22]:
#cumulative sum of columns
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [26]:
np.sum(a)

45